AR Detection UI
space-concordia-robotics/robotics-orin-gui pull request #3
Opened 2024-05-29 02:27 UTC by AmirDehestani

Created a new UI component for displaying the detected AR tags. For each detected AR tag, this component displays the  tag ID, the generated ArUco tag, and its pose.

Suggestion for future implementation: Add a feature that allows the user to choose the ArUco dictionary.

2024-06-13 22:25 UTC, AmirDehestani commented
All bugs were fixed, and all suggested features were added. Ready to merge after review.

2024-06-21 14:04 UTC, vexandmore requested changes

2024-06-21 14:04 UTC, vexandmore commented on scripts/python/aruco_generate_marker.py
> +        parser.add_argument('--border', default=20, type=int,
Are you using the border argument?

2024-06-21 14:04 UTC, vexandmore commented on src/app/ar-ui/ar-display/ar-display.component.spec.ts
> +    await TestBed.configureTestingModule({
Is this a unit test file? I'm not sure why there's references to tests in this file

2024-06-21 14:04 UTC, vexandmore commented on src/app/ar-ui/ar-tag/ar-tag.component.spec.ts
> +    await TestBed.configureTestingModule({
again, not sure what the point of this test is

2024-06-21 14:04 UTC, vexandmore commented on src/app/services/ros.service.ts
> +  subscribeToArucoMarkers(callback: (data: ArucoMarker) => void) {
out of interest, why is the aruco marker subscriber not subscribed to the topic in its constructor?

2024-07-06 16:11 UTC, AmirDehestani commented on src/app/ar-ui/ar-display/ar-display.component.spec.ts
> +    await TestBed.configureTestingModule({
Auto-generated by Angular CLI. Not needed in our case.

2024-07-06 16:18 UTC, AmirDehestani commented on src/app/services/ros.service.ts
> +  subscribeToArucoMarkers(callback: (data: ArucoMarker) => void) {
Like this, any subscribeTo[Topic] method can be called by other components only when they are needed.

2024-07-06 16:21 UTC, AmirDehestani commented on scripts/python/aruco_generate_marker.py
> +        parser.add_argument('--border', default=20, type=int,
Removed

2024-08-16 20:29 UTC, merged